services:
    video:
      build: 
        context: .
        dockerfile: docker/video.Dockerfile
        platforms:
          - ${TARGETPLATFORM:-linux/${HOSTARCH:-amd64}}
      environment:
        - LOCALHOST=${LOCALHOST:-false}
      volumes:
        - ./data/json:/etc/nginx/json
        - ./data/vod:/etc/nginx/vod
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/kalturalog.txt:/etc/logrotate.d/nginx
      ports:
        - 3000:80
      restart: unless-stopped
      networks:
        - aevumflow
  
    app:
      build: 
        context: .
        dockerfile: docker/app.Dockerfile
        platforms:
          - ${TARGETPLATFORM:-linux/${HOSTARCH:-amd64}}
      command: npm run start
      volumes: 
        - ./data/json:/app/data/json
        - ./data/vod:/app/data/vod
        - ./data/uploads:/app/data/uploads 
        - ./data/thumbnails:/app/data/thumbnails
        - ./src:/app/src
        - ./prisma/data.db:/app/prisma/data.db
      networks:
        - aevumflow
      depends_on:
        - minio

    minio:
      image: minio/minio
      platform: ${TARGETPLATFORM:-linux/${HOSTARCH:-amd64}}
      ports:
        - "9000:9000"
        - "${MINIO_CONSOLE_PORT:-9001}:9001"
      volumes:
        - ./data/minio:/data
      environment:
        - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
        - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      command: server /data --console-address ":9001"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      networks:
        - aevumflow
  
networks:
  aevumflow:
    driver: bridge
