services:
    video:
      build: 
        context: .
        dockerfile: docker/video.Dockerfile
      volumes:
        - ./data/json:/etc/nginx/json
        - ./data/vod:/etc/nginx/vod
      ports:
        - 3000:80
      restart: unless-stopped
      networks:
        - kaltura
  
    app:
      build: 
        context: .
        dockerfile: docker/app.Dockerfile
      command: npm run start
      volumes: 
        - ./data/json:/app/data/json
        - ./data/vod:/app/data/vod
        - ./data/uploads:/app/data/uploads 
        - ./src:/app/src
      networks:
        - kaltura
  
networks:
  kaltura:
    driver: bridge